chore: bump husky version

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,13 +1,11 @@
 #!/bin/sh
 
-. "$(dirname "$0")/_/husky.sh"
-
 BRANCH=$(git rev-parse --abbrev-ref HEAD)
-REGEX="^(main|((feat|fix|docs|chore|refactor|release|test)\/.+))$"
+REGEX="^(main|((feat|fix|docs|chore|refactor|release|test|hotfix)\/.+))$"
 
-if ! [[ $BRANCH =~ $REGEX ]]; then
-  echo "Your commit was rejected due to branching name"
-  echo "Please rename your branch with $REGEX syntax"
-  echo "Required prefix can be one of: feat|fix|docs|chore|refactor|release|test"
+if ! echo "$BRANCH" | grep -Eq "$REGEX"; then
+  echo "Your commit was rejected due to invalid branch name: '$BRANCH'"
+  echo "Please rename your branch to follow one of the accepted formats:"
+  echo "  - feat/*, fix/*, docs/*, chore/*, refactor/*, release/*, test/*, hotfix/*"
   exit 1
 fi
